project:
  type: website
  render:
    - "*.qmd"
    - "!slides/"
  resources: 
    - "slides/*.html"
    - "slides/*.pdf"
    - "slides/img/"
    - "slides/libs/"
    - "slides/css/"
    - "slides/*_files/"
  preview: 
    port: 4444

website:
  title: "PhD Experiences Website"

  repo-url: "https://github.com/Leslie-Lu/20260429_phd_experiences"
  repo-actions: [source, issue]

  navbar:
    pinned: true
    left:
      - href: index.qmd
        text: Home
    right:
      - icon: github
        href: "https://github.com/Leslie-Lu/20260429_phd_experiences"


author:
- name: Zhen Lu
  url: "https://leslie-lu.github.io/"
  affiliation: Sun Yat-sen University
  email: luzh29@mail2.sysu.edu.cn
  orcid: 0000-0002-3481-6310

format:
  html:
    theme:
      - zephyr
      - brand
    toc: true
